# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "James Crowley"
fulltitle: "James Crowley - CTO-ing, full stack engineering and startups"

# A description of your site for social meta tag, search engines, and feed.xml
description: "James Crowley is an entrepreneurial CTO with 16+ years of experience building software, technology teams and businesses. James co-founded FundApps, a fintech SaaS platform helping global financial institutions comply with regulation."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://jamescrowley.net"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About me
  url: /about-me/
- text: Talks and Slides
  url: /talks-slides/
- text: Blog
  url: /blog/

# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Author information - author info at the bottom of the post
author_name: "James Crowley"
author_bio: "CTO-ing, full stack engineering and startups"
author_url:  "http://justgoodthemes.com"
author_image: /assets/images/authorimage.png

# Social links in the site footer
twitter_username: "jamescrowley"
github_username: "jamescrowley"
instagram_username: "jc_barefoot"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/page/:num/'
plugins: [jekyll-paginate]

# Permalinks
permalink: /:year/:month/:day/:title/

markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
